# Generated by Django 4.2.2 on 2023-06-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationrunresult',
            name='OK',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replicationrunresult',
            name='bytes_copied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replicationrunresult',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replicationrunresult',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replicationrunresult',
            name='warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='replication',
            name='dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='replication',
            name='dst_file_to_check',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='replication',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='replication',
            name='post_cmd',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='replication',
            name='pre_cmd',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='replication',
            name='retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='replication',
            name='src_file_to_check',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='replicationrunresult',
            name='dry_run',
            field=models.BooleanField(default=False),
        ),
    ]
