# Generated by Django 4.2.2 on 2023-06-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0002_replicationrunresult_ok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replication',
            name='dest',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='replication',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='replication',
            name='src',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
