# Generated by Django 4.2.2 on 2023-06-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0003_alter_replication_dest_alter_replication_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replication',
            name='dst_file_to_check',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='replication',
            name='post_cmd',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='replication',
            name='pre_cmd',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='replication',
            name='src_file_to_check',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='replicationrunresult',
            name='bytes_copied',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='replicationrunresult',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='replicationrunresult',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start'),
        ),
    ]
