# Generated by Django 4.2.2 on 2023-07-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0005_replicationtask_replication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationtask',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
