# Generated by Django 4.2.2 on 2023-07-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0006_replicationtask_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replication',
            name='options',
            field=models.CharField(default='-axv --delete', max_length=512),
        ),
    ]
