# Generated by Django 4.2.2 on 2023-07-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0007_alter_replication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationschedule',
            name='dom',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='replicationschedule',
            name='dow',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='replicationschedule',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='replicationschedule',
            name='hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='replicationschedule',
            name='minute',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='replicationschedule',
            name='month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='replicationschedule',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='replicationschedule',
            name='replication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='replicator.replication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replicationschedule',
            name='second',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='replicationschedule',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
