# Generated by Django 4.2.2 on 2023-07-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0008_replicationschedule_dom_replicationschedule_dow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationtask',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
