# Generated by Django 4.2.2 on 2023-08-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0009_replicationtask_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationtask',
            name='schedule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='replicator.replicationschedule'),
        ),
    ]
