# Generated by Django 4.2.4 on 2023-08-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0011_replicationschedule_every_n_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationschedule',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
