# Generated by Django 4.2.4 on 2023-08-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0013_remove_replicationschedule_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationschedule',
            name='hourly',
            field=models.BooleanField(default=False),
        ),
    ]
