# Generated by Django 4.2.4 on 2023-08-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0014_replicationschedule_hourly'),
    ]

    operations = [
        migrations.AddField(
            model_name='replication',
            name='check_ping',
            field=models.BooleanField(default=True),
        ),
    ]
