# Generated by Django 4.2.4 on 2023-08-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0015_replication_check_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationtask',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
