# Generated by Django 4.2.4 on 2023-09-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0016_replicationtask_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationtask',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_created'),
        ),
    ]
