# Generated by Django 4.2.4 on 2023-09-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0017_replicationtask_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_dry_run', models.BooleanField(default=False)),
                ('rsync_binary', models.CharField(default='rsync', max_length=512)),
            ],
        ),
    ]
