# Generated by Django 4.2.4 on 2023-09-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0018_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='rsync_binary',
            new_name='rsync_executable',
        ),
    ]
