# Generated by Django 4.2.4 on 2023-12-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0019_rename_rsync_binary_settings_rsync_executable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replication',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='replicationschedule',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='replicationtask',
            options={'ordering': ('-date_created',)},
        ),
    ]
