# Generated by Django 4.2.4 on 2023-12-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replicator', '0020_alter_replication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='replicationtask',
            options={'ordering': ('-date_created', '-start')},
        ),
    ]
